### ISSUE TITLE
vivo xplay5，android5.1.1

### ISSUE THREAD

**Issue by MarshallMathersIII** [uccmawei/FingerprintIdentify#19]
vivo xplay5，android5.1.1机型支持手机指纹功能，但验证失败后只执行一次onNotMatch()方法，之后不会执行

**Comment by uccmawei** [comment]
@MarshallMathersIII 麻烦补充一下相关代码以及操作情况和截图，不然我也没办法判断。

**Comment by uccmawei** [comment]
@MarshallMathersIII 你可以试下直接扫二维码下载demo试下，再截个图看下？

**Comment by MarshallMathersIII** [comment]
下载你的demo测试，确实支回调一次onNotMatch，之后就没有任何反馈了，构造时也未捕获到异常，vivo xplay5，android5.1.1，我直接对机型做了判断禁止使用指纹

**Comment by uccmawei** [comment]
@MarshallMathersIII 真是给跪了，难道它的API除了拷贝6.0的那套外还改动了回调逻辑不成？

你试下把我的项目下载去运行，把类AndroidFingerprint的needToCallDoIdentifyAgainAfterNotMatch方法改回return true，再试下。也许问题是出在这里。

**Comment by missAllen** [comment]
vivo5.1的直接崩溃了

**Comment by missAllen** [comment]
`java.lang.AbstractMethodError: abstract method "void android.hardware.fingerprint.FingerprintManager$AuthenticationCallback.onAuthenticationHelp(int, java.lang.CharSequence)"
                                                       at com.lib.fingerprintidentify.impl.AndroidFingerprint$1.onAuthenticationHelp(AndroidFingerprint.java:52)
                                                       at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAcquiredResult(FingerprintManager.java:932)
                                                       at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:759)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

**Comment by uccmawei** [comment]
@missAllen 错误信息只有这些吗？感觉不是很完整的？

**Comment by missAllen** [comment]
@uccmawei 这是主要的信息

**Comment by uccmawei** [comment]
因为产商的定制化太严重导致无法稳定适配，所以暂时先恢复6.0的版本限制，如果大家需要支持安卓6.0以下的设备，建议自行拓展 AndroidFingerprint.java 类来实现。
